import Foundation

// Unicode characters back to the LaTeX that produces them.
//
// Generated by inverting the command tables `EditorMath` declares, so the two
// can't disagree about what a symbol is called. Every command here is one the
// renderer's parser accepts, which is the property that matters: LaTeX it
// couldn't parse would render as an error rather than as a formula.
//
// ASCII is deliberately absent — those characters mean themselves in LaTeX, and
// the few needing an escape are handled where the text is escaped.
let mathMLSymbols: [String: String] = [
    "£": "\\pounds", "§": "\\S", "¬": "\\neg", "®": "\\circledR", "°": "\\degree", "±": "\\pm",
    "¶": "\\P", "·": "\\cdot", "×": "\\times", "÷": "\\div", "ı": "\\imath", "ȷ": "\\jmath",
    "Γ": "\\Gamma", "Δ": "\\Delta", "Θ": "\\Theta", "Λ": "\\Lambda", "Ξ": "\\Xi", "Π": "\\Pi",
    "Σ": "\\Sigma", "Υ": "\\Upsilon", "Φ": "\\Phi", "Ψ": "\\Psi", "Ω": "\\Omega",
    "α": "\\alpha", "β": "\\beta", "γ": "\\gamma", "δ": "\\delta", "ε": "\\varepsilon",
    "ζ": "\\zeta", "η": "\\eta", "θ": "\\theta", "ι": "\\iota", "κ": "\\kappa",
    "λ": "\\lambda", "μ": "\\mu", "ν": "\\nu", "ξ": "\\xi", "ο": "\\omicron", "π": "\\pi",
    "ρ": "\\rho", "ς": "\\varsigma", "σ": "\\sigma", "τ": "\\tau", "υ": "\\upsilon",
    "φ": "\\varphi", "χ": "\\chi", "ψ": "\\psi", "ω": "\\omega", "ϑ": "\\vartheta",
    "ϕ": "\\phi", "ϖ": "\\varpi", "ϱ": "\\varrho", "ϵ": "\\epsilon", "‖": "\\lVert",
    "†": "\\dag", "‡": "\\ddag", "…": "\\ldots", "′": "\\prime", "″": "\\dprime",
    "ℏ": "\\hbar", "ℑ": "\\Im", "ℓ": "\\ell", "℘": "\\wp", "ℜ": "\\Re", "℧": "\\mho",
    "ℵ": "\\aleph", "ℶ": "\\beth", "←": "\\leftarrow", "↑": "\\uparrow", "→": "\\to",
    "↓": "\\downarrow", "↔": "\\leftrightarrow", "↕": "\\updownarrow", "↖": "\\nwarrow",
    "↗": "\\nearrow", "↘": "\\searrow", "↙": "\\swarrow", "↚": "\\nleftarrow",
    "↛": "\\nrightarrow", "↦": "\\mapsto", "↩": "\\hookleftarrow", "↪": "\\hookrightarrow",
    "↼": "\\leftharpoonup", "↽": "\\leftharpoondown", "⇀": "\\rightharpoonup",
    "⇁": "\\rightharpoondown", "⇌": "\\rightleftharpoons", "⇐": "\\Leftarrow",
    "⇑": "\\Uparrow", "⇒": "\\Rightarrow", "⇓": "\\Downarrow", "⇔": "\\Leftrightarrow",
    "⇕": "\\Updownarrow", "⇝": "\\leadsto", "∀": "\\forall", "∂": "\\partial", "∃": "\\exists",
    "∄": "\\nexists", "∅": "\\emptyset", "∇": "\\nabla", "∈": "\\in", "∉": "\\notin",
    "∋": "\\ni", "∏": "\\prod", "∐": "\\coprod", "∑": "\\sum", "∓": "\\mp", "∖": "\\setminus",
    "∗": "\\ast", "∘": "\\circ", "∙": "\\bullet", "√": "\\surd", "∝": "\\propto",
    "∞": "\\infty", "∠": "\\angle", "∡": "\\measuredangle", "∣": "\\mid", "∤": "\\nmid",
    "∥": "\\parallel", "∧": "\\wedge", "∨": "\\vee", "∩": "\\cap", "∪": "\\cup", "∫": "\\int",
    "∬": "\\iint", "∭": "\\iiint", "∮": "\\oint", "∯": "\\oiint", "∴": "\\therefore",
    "∵": "\\because", "∼": "\\sim", "≀": "\\wr", "≃": "\\simeq", "≅": "\\cong",
    "≈": "\\approx", "≊": "\\approxeq", "≍": "\\asymp", "≐": "\\doteq", "≔": "\\coloneqq",
    "≠": "\\neq", "≡": "\\equiv", "≤": "\\leq", "≥": "\\geq", "≪": "\\ll", "≫": "\\gg",
    "≺": "\\prec", "≻": "\\succ", "⊂": "\\subset", "⊃": "\\supset", "⊆": "\\subseteq",
    "⊇": "\\supseteq", "⊈": "\\nsubseteq", "⊉": "\\nsupseteq", "⊊": "\\subsetneq",
    "⊋": "\\supsetneq", "⊎": "\\uplus", "⊑": "\\sqsubseteq", "⊒": "\\sqsupseteq",
    "⊓": "\\sqcap", "⊔": "\\sqcup", "⊕": "\\oplus", "⊖": "\\ominus", "⊗": "\\otimes",
    "⊘": "\\oslash", "⊙": "\\odot", "⊞": "\\boxplus", "⊟": "\\boxminus", "⊠": "\\boxtimes",
    "⊡": "\\boxdot", "⊢": "\\vdash", "⊣": "\\dashv", "⊤": "\\top", "⊥": "\\bot",
    "⊨": "\\models", "⋀": "\\bigwedge", "⋁": "\\bigvee", "⋂": "\\bigcap", "⋃": "\\bigcup",
    "⋄": "\\diamond", "⋅": "\\cdot", "⋆": "\\star", "⋈": "\\bowtie", "⋉": "\\ltimes",
    "⋊": "\\rtimes", "⋮": "\\vdots", "⋯": "\\cdots", "⋱": "\\ddots", "⌈": "\\lceil",
    "⌉": "\\rceil", "⌊": "\\lfloor", "⌋": "\\rfloor", "⌢": "\\frown", "⌣": "\\smile",
    "■": "\\blacksquare", "□": "\\square", "△": "\\triangle", "▹": "\\triangleright",
    "▽": "\\bigtriangledown", "◃": "\\triangleleft", "◇": "\\Diamond", "◯": "\\bigcirc",
    "♠": "\\spadesuit", "♡": "\\heartsuit", "♢": "\\diamondsuit", "♣": "\\clubsuit",
    "♭": "\\flat", "♮": "\\natural", "♯": "\\sharp", "✓": "\\checkmark", "✠": "\\maltese",
    "⟨": "\\langle", "⟩": "\\rangle", "⟵": "\\longleftarrow", "⟶": "\\longrightarrow",
    "⟷": "\\longleftrightarrow", "⟸": "\\impliedby", "⟹": "\\implies", "⟺": "\\iff",
    "⟼": "\\longmapsto", "⨀": "\\bigodot", "⨁": "\\bigoplus", "⨂": "\\bigotimes",
    "⨄": "\\biguplus", "⨆": "\\bigsqcup", "⨿": "\\amalg", "⩽": "\\leqslant", "⩾": "\\geqslant",
    "⪯": "\\preceq", "⪰": "\\succeq",
]
